version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mixer4422
      MYSQL_DATABASE: portfolio
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  spring-boot:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mixer4422
    depends_on:
      - mysql
  nextjs:
    build: ./portfolio
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot
